# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boltdbweb < Formula
  desc "Bolt DB Web UI"
  homepage "https://github.com/Isan-Rivkin/boltdbweb"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Isan-Rivkin/boltdbweb/releases/download/v1.0.1/boltdbweb_1.0.1_darwin_arm64.tar.gz"
      sha256 "5ea29781e7cd3a7beed79e4e34587d10508d7b2b647b11a2491f44f8a69e0bcc"

      def install
        bin.install "boltdbweb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Isan-Rivkin/boltdbweb/releases/download/v1.0.1/boltdbweb_1.0.1_darwin_amd64.tar.gz"
      sha256 "3368cb202da4291c4e88f56cb3d5c6548d3ed7d631726909e881c4936590166d"

      def install
        bin.install "boltdbweb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Isan-Rivkin/boltdbweb/releases/download/v1.0.1/boltdbweb_1.0.1_linux_arm64.tar.gz"
      sha256 "a765c48ab0a6d08c786232a938a45f9264621ed71447cd394299cd4141ee3fa9"

      def install
        bin.install "boltdbweb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Isan-Rivkin/boltdbweb/releases/download/v1.0.1/boltdbweb_1.0.1_linux_amd64.tar.gz"
      sha256 "20ba4caf3d6ec4a4d03174f82d1f1b3106228c904e1e45a0e860a5953465d57f"

      def install
        bin.install "boltdbweb"
      end
    end
  end

  depends_on "git"
end
