# This file was generated by GoReleaser. DO NOT EDIT.
class Kq < Formula
  desc "Cli tool for querying all your kubernetes clusters"
  homepage "https://github.com/Isan-Rivkin/kube_query"
  version "0.1.1"
  if OS.mac?
    url "https://github.com/Isan-Rivkin/kube_query/releases/download/v0.1.1/kube_query_0.1.1_darwin_amd64.tar.gz"
    sha256 "3c48bbf6f4833b7365c9aa9c3f8152ce0a223cc0047a90340d3593482eeb42eb"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Isan-Rivkin/kube_query/releases/download/v0.1.1/kube_query_0.1.1_linux_amd64.tar.gz"
    sha256 "7234281c23bd303b16d97be4b249ec446ae6ed115db9939b25af3e3bddd9500d"
  end
  depends_on "git"
  def install
    bin.install "kq"
  end
end
