# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class R53 < Formula
  desc "Cli tool for Route53 to quickly query values of records"
  homepage "https://github.com/Isan-Rivkin/route53-cli"
  version "0.4.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Isan-Rivkin/route53-cli/releases/download/v0.4.2/route53-cli_0.4.2_darwin_arm64.tar.gz"
      sha256 "c061cfa9e05a80f853888b8b8bd2b9cd1386b8723126768a6b3707929da1d2a0"

      def install
        bin.install "r53"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Isan-Rivkin/route53-cli/releases/download/v0.4.2/route53-cli_0.4.2_darwin_amd64.tar.gz"
      sha256 "74f5b9db400889b414e054f9c152f9958507bb5144329d0660cf005f44f11da3"

      def install
        bin.install "r53"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Isan-Rivkin/route53-cli/releases/download/v0.4.2/route53-cli_0.4.2_linux_amd64.tar.gz"
      sha256 "0edb0cfc56ceeeed79f8587c59b10631e724b6b8747f0200f617dbf99b3b98ac"

      def install
        bin.install "r53"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Isan-Rivkin/route53-cli/releases/download/v0.4.2/route53-cli_0.4.2_linux_arm64.tar.gz"
      sha256 "5ae93f524fe7c8a1ef8a8984ed6040f27d3307657f1f8a715743e58c82470079"

      def install
        bin.install "r53"
      end
    end
  end

  depends_on "git"
end
