# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Surf < Formula
  desc "CLI Text Search across your infrastructure platforms"
  homepage "https://github.com/Isan-Rivkin/surf"
  version "2.0.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Isan-Rivkin/surf/releases/download/v2.0.0/surf_2.0.0_darwin_amd64.tar.gz"
      sha256 "7f7ca2e905ad3142d40a07f425090486fb08c4846cd7a554acae1a500866c2ff"

      def install
        bin.install "surf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Isan-Rivkin/surf/releases/download/v2.0.0/surf_2.0.0_darwin_arm64.tar.gz"
      sha256 "3602de5c715c59cc5e7c8283d6c211402063f2946029aef1e6c370da456a399b"

      def install
        bin.install "surf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Isan-Rivkin/surf/releases/download/v2.0.0/surf_2.0.0_linux_arm64.tar.gz"
      sha256 "e6c7fb322ec18da5c3f166387fc959d7c4769f9092fc6f39f20beddee6876424"

      def install
        bin.install "surf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Isan-Rivkin/surf/releases/download/v2.0.0/surf_2.0.0_linux_amd64.tar.gz"
      sha256 "6f752b438fbbb8bcbce25bb3a4a25450c7ff3fb688cf0abe4231069f9d426285"

      def install
        bin.install "surf"
      end
    end
  end
end
