# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Surf < Formula
  desc "CLI Text Search across your infrastructure platforms"
  homepage "https://github.com/Isan-Rivkin/surf"
  version "1.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Isan-Rivkin/surf/releases/download/v1.1.2/surf_1.1.2_darwin_arm64.tar.gz"
      sha256 "a4e5d282170c8ced129eed6d5e24f7a046af0ff76b57af48521e787bb8eecce0"

      def install
        bin.install "surf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Isan-Rivkin/surf/releases/download/v1.1.2/surf_1.1.2_darwin_amd64.tar.gz"
      sha256 "6e6f2b6e458499cbd5dc583030581245d7c0df0087187317cd6cd46c9bcc9371"

      def install
        bin.install "surf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Isan-Rivkin/surf/releases/download/v1.1.2/surf_1.1.2_linux_amd64.tar.gz"
      sha256 "c737f6e991851ef0ba5cc3e81f9040b7d724a3f712e24c480efce0765f24e5e5"

      def install
        bin.install "surf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Isan-Rivkin/surf/releases/download/v1.1.2/surf_1.1.2_linux_arm64.tar.gz"
      sha256 "661fe0839b0a35cff69ef92cb96b6cafb37505371c259e9e1f6148ad386b7a9e"

      def install
        bin.install "surf"
      end
    end
  end

  depends_on "git"
end
